project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://www.poromics.org # you must change this appropriately for RSS feeds to work properly
  title: "poromics"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - blog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/poromics

format:
  html:
    theme:
      - materia
    css: styles.css
