project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://www.poromics.org # you must change this appropriately for RSS feeds to work properly
  title: "poromics"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: https://pnmlib.poromics.org
        text: pnmlib
      - href: https://www.github.com/PMEAL/kabs
        text: kabs
      - blog.qmd
      - about.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/poromics

format:
  html:
    theme:
      - materia
    css: styles.css
